del /S *.~*
del /S *.dcu
del /S *.dsk
del /S *.dof
del /S *.obj
del /S *.hpp
del /S *.ddp
del /S *.mps
del /S *.mpt
del /S *.bak
del /S *.o
del /S *.ppu
C:\strip /B "C:\pas\Delphi\cancel\cancel.exe"